name: Get repository name

on:
  workflow_call:
    outputs:
        repo_name:
            description: "The name of the repository of the caller workflow"
            value: ${{ jobs.get-repo-name-job.outputs.repo-name }}
jobs:
  get-repo-name-job:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ get-repo-name-step.outputs.output }}
    steps:
      - id: get-repo-name-step
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT