name: Read current tag from changelog

on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: 'master'
        required: false
        description: 'Branch from which the changelog file will be read'
    outputs:
      current_tag:
        description: "Current tag from changelog"
        value: ${{ jobs.read-current-tag-job.outputs.current_tag }}

jobs:
  read-current-tag-job:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ steps.regex_match.outputs.match }}
    steps:
      # check out repository
      - uses: actions/checkout@v3

      # read changelog file
      - name: Read CHANGELOG.md
        id: read_changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: ${{ inputs.branch }}
          path: CHANGELOG.md

      # find current tag in changelog file
      - name: Find current tag in CHANGELOG
        id: regex_match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.read_changelog.outputs.content }}
          regex: '^(#\s\[current tag\]\s+\-\s+.+)$'