name: Find and replace tags with new ones

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: 'The name of the repository which now has a new tag or branch'
      branch_or_tag:
        type: string
        required: true
        description: 'The tag or branch to replace with'
      is_tag:
        type: boolean
        required: true
        description: 'Flag to tell whether a tag or a branch is passed as input'

jobs:
  find-and-replace-jnkSharedLibraryBranch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !inputs.is_tag }} && ${{ inputs.repo }} == jnk__shared_library
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSharedLibraryBranch
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSharedLibraryBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSharedLibraryBranch = '${{ inputs.branch_or_tag }}'
#          include: src/test/resources/**
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4


  find-and-replace-jnkSwcIntBranch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !inputs.is_tag }} && ${{ inputs.repo }} == jnk__swc_integration
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSwcIntBranch
        uses: jacobtomlinson/gha-find-replace@v3
        if: ${{ inputs.repo }} == jnk__swc_integration
        with:
          find: jnkSwcIntBranchBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcIntBranchBranch = '${{ inputs.branch_or_tag }}'
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

  find-and-replace-jnkSwcSwuPipelineBranch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !inputs.is_tag }} && ${{ inputs.repo }} == jnk__swc_swu_pipeline
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSwcSwuPipelineBranch
        uses: jacobtomlinson/gha-find-replace@v3
        if: ${{ inputs.repo }} == jnk__swc_swu_pipeline
        with:
          find: jnkSwcSwuPipelineBranchBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcSwuPipelineBranchBranch = '${{ inputs.branch_or_tag }}'
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
#  find-and-replace-tag-job:
#    runs-on: ubuntu-latest
#    if: ${{ inputs.is_tag }}
#    steps:
#      - run: |
#          echo ${{ inputs.repo }}
#          echo ${{ inputs.branch_or_tag }}
#          echo "is tag"