name: Find and replace tags with new ones

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: 'The name of the repository which now has a new tag or branch'
      branch_or_tag:
        type: string
        required: true
        description: 'The tag or branch to replace with'
      is_tag:
        type: string
        required: true
        description: 'Flag to tell whether a tag or a branch is passed as input'

jobs:
  find-and-replace-jnkSharedLibraryBranch:
    if: ${{ inputs.repo }} == 'jnk__shared_library'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSharedLibraryBranch
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSharedLibraryBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSharedLibraryBranch = '${{ inputs.branch_or_tag }}'
#          include: src/test/resources/**
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4


  find-and-replace-jnkSwcIntBranch:
    if: ${{ inputs.repo }} == 'jnk__swc_integration'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSwcIntBranch
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSwcIntBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcIntBranch = '${{ inputs.branch_or_tag }}'
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

  find-and-replace-jnkSwcSwuPipelineBranch:
    if: ${{ inputs.repo }} == 'jnk__swc_swu_pipeline'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace jnkSwcSwuPipelineBranch
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSwcSwuPipelineBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcSwuPipelineBranch = '${{ inputs.branch_or_tag }}'
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
#  find-and-replace-tag-job:
#    runs-on: ubuntu-latest
#    if: ${{ inputs.is_tag }}
#    steps:
#      - run: |
#          echo ${{ inputs.repo }}
#          echo ${{ inputs.branch_or_tag }}
#          echo "is tag"