name: Find and replace tags with new ones

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: 'The name of the repository which now has a new tag or branch'
      branch_or_tag:
        type: string
        required: true
        description: 'The tag or branch to replace with'
      is_tag:
        type: boolean
        required: true
        description: 'Flag to tell whether a tag or a branch is passed as input'

jobs:
  find-and-replace-branch-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !inputs.is_tag }}
#    env:
#      if: ${{ inputs.repo }} == jnk__shared_library
#      OLD_BRANCH_TAG: "jnkSharedLibraryBranch\s*=\s*'.+'"
#      NEW_BRANCH_TAG: ${{format("jnkSharedLibraryBranch = '\refs\tags\{0}'", ${{inputs.branch_or_tag}}) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "xxx"
          replace: "jnkSharedLibraryBranch2"
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

#  find-and-replace-tag-job:
#    runs-on: ubuntu-latest
#    if: ${{ inputs.is_tag }}
#    steps:
#      - run: |
#          echo ${{ inputs.repo }}
#          echo ${{ inputs.branch_or_tag }}
#          echo "is tag"