name: 09 find and replace with branch name

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: 'The name of the repository which now has a new tag or branch'
      branch:
        type: string
        required: true
        description: 'The tag or branch to be replaced with'

jobs:
  find-and-replace-with-new-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature_branch
      - name: Find and Replace jnkSharedLibraryBranch
        if: ${{ inputs.repo == 'jnk__shared_library' }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSharedLibraryBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSharedLibraryBranch = '${{ inputs.branch }}'
#          include: src/test/resources/**
          exclude: .github/**
      - name: Find and Replace jnkSwcIntBranch
        if: ${{ inputs.repo == 'jnk__swc_integration' }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSwcIntBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcIntBranch = '${{ inputs.branch }}'
          exclude: .github/**
      - name: Find and Replace jnkSwcSwuPipelineBranch
        if: ${{ inputs.repo == 'jnk__swc_swu_pipeline' }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: jnkSwcSwuPipelineBranch\s*=\s*[/_A-Za-z\d\.'-]+
          replace: jnkSwcSwuPipelineBranch = '${{ inputs.branch }}'
          exclude: .github/**
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4