# Actions to create a new git tag
#
# author: Manuel Eberle (EUNMSFB)
# mail: extern.manuel.eberle@audi.de
# creation date: 22.11.2022
# edited by Wei Huang (ADI44PX) at 21.09.2023
#

name: Create Git Tag Workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: 'Tag name'
      branch:
        type: string
        required: true
        description: 'Branch from which the tag is to be created'
      runner:
        required: true
        type: string
        description: "The runner id as String"

jobs:
  create-tag:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          branch: ${{ inputs.branch }}
      - name: create tag
        run: |
          git tag ${{ inputs.tag }} ${{ inputs.branch }}
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4