name: Test reusable workflow
on:
  issues:
    types: [opened]
jobs:
  job1:
    uses: wilhelmhuang/weihuang/.github/workflows/04-get-repo-name.yml@master
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
        - run: echo ${{ needs.job1.outputs.repo-name }}