name: Test reading file
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read CHANGELOG.md(master)
        id: changelog_master
        uses: jaywcjlove/github-action-read-file@main
        with:
            branch: master
            path: CHANGELOG.md
      - name: find current tag in changelog
        env:
          CHANGELOG_CONTENT: ${{ steps.changelog_master.outputs.content }}
        if: contains('$CHANGELOG_CONTENT', "[current tag]")
        run: echo "found"
