name: Test reading file
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read CHANGELOG.md(master)
        id: changelog_master
        uses: jaywcjlove/github-action-read-file@main
        with:
            branch: master
            path: CHANGELOG.md
      - name: check if current tag is set
        env:
          CHANGELOG_CONTENT: ${{ steps.changelog_master.outputs.content }}
        if: contains(env.CHANGELOG_CONTENT, '[current tag]')
        run: echo "found"
      - name: find current tag in changelog
        id: regex_match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.changelog_master.outputs.content }}
          regex: '(\[current tag\])'
      - name: print found tag
        run: |
          echo '${{ steps.regex_match.outputs.match }}'
          echo '${{ steps.regex_match.outputs.group1 }}'
          echo '${{ steps.regex_match.outputs.group2 }}'
          echo '${{ steps.regex_match.outputs.group3 }}'

