name: test find and replace branch
on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/09-find-and-replace-with-branch-name.yml
    with:
      repo: jnk__shared_library
      branch_or_tag: lib/new_branch

#  job2:
#    uses: ./.github/workflows/08-find-and-replace.yml
#    with:
#      repo: jnk__swc_integration
#      branch_or_tag: swc/new_branch
#      is_tag: false
#  job3:
#    uses: ./.github/workflows/08-find-and-replace.yml
#    with:
#      repo: jnk__swc_swu_pipeline
#      branch_or_tag: swu/new_branch
#      is_tag: false


#  job2:
#    runs-on: ubuntu-latest
#    needs: job1
#    steps:
#      - run: echo ${{ needs.job1.outputs.modifiedFiles }}

#  job3:
#    needs: job0
#    uses: ./.github/workflows/08-find-and-replace.yml
#    with:
#      repo: ${{ needs.job0.outputs.repo_name }}
#      branch_or_tag: 456
#      is_tag: true

