name: Test find and replace tag
on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/10-find-and-replace-with-new-tag.yml.yml
    with:
      repo: jnk__swc_swu_pipeline
      tag: 3.0.1
      runner: ubuntu-latest