name: Update tag usages
on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/trigger-find-and-replace-tag.yml
    with:
      repo: jnk__swc_swu_pipeline
      tag: 3.0.1
      runner: ubuntu-latest
    secrets: inherit